#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Aug 09, 2021 03:12:55 PM WAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

from PIL import Image, ImageTk

import Banking_App_support
import os.path


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    Banking_App_support.set_Tk_var()
    top = Toplevel1(root)
    Banking_App_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    Banking_App_support.set_Tk_var()
    top = Toplevel1(w)
    Banking_App_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=
        [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("600x450+384+191")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        # ---------------USER BANKING FRAME------------------------------------
        self.User_banking = tk.Frame(top)
        self.User_banking.place(relx=0.183, rely=0.042, relheight=0.885
                                , relwidth=0.575)
        self.User_banking.configure(relief='groove')
        self.User_banking.configure(borderwidth="2")
        self.User_banking.configure(relief="groove")
        self.User_banking.configure(background="#d9d9d9")

        self.Welcome_Reg = tk.Label(self.User_banking)
        self.Welcome_Reg.place(relx=0.058, rely=0.126, height=21, width=70)
        self.Welcome_Reg.configure(background="#d9d9d9")
        self.Welcome_Reg.configure(disabledforeground="#a3a3a3")
        self.Welcome_Reg.configure(font="-family {Verdana} -size 10")
        self.Welcome_Reg.configure(foreground="#000000")
        self.Welcome_Reg.configure(text='''Welcome :''')

        self.Entry_button = tk.Entry(self.User_banking)
        self.Entry_button.place(relx=0.435, rely=0.126, height=20, relwidth=0.33)

        self.Entry_button.configure(background="white")
        self.Entry_button.configure(disabledforeground="#a3a3a3")
        self.Entry_button.configure(font="TkFixedFont")
        self.Entry_button.configure(foreground="#000000")
        self.Entry_button.configure(insertbackground="black")

        self.Bills_Payment_Reg = tk.Label(self.User_banking)
        self.Bills_Payment_Reg.place(relx=0.058, rely=0.276, height=21, width=90)

        self.Bills_Payment_Reg.configure(background="#d9d9d9")
        self.Bills_Payment_Reg.configure(disabledforeground="#a3a3a3")
        self.Bills_Payment_Reg.configure(font="-family {Verdana} -size 10")
        self.Bills_Payment_Reg.configure(foreground="#000000")
        self.Bills_Payment_Reg.configure(text='''Bills Payment''')

        self.Bank_Transfer_Reg = tk.Label(self.User_banking)
        self.Bank_Transfer_Reg.place(relx=0.029, rely=0.402, height=21
                                     , width=100)
        self.Bank_Transfer_Reg.configure(background="#d9d9d9")
        self.Bank_Transfer_Reg.configure(disabledforeground="#a3a3a3")
        self.Bank_Transfer_Reg.configure(font="-family {Verdana} -size 10")
        self.Bank_Transfer_Reg.configure(foreground="#000000")
        self.Bank_Transfer_Reg.configure(text='''Bank Transfer''')

        self.USER_BANKING_INTERFACE_Reg = tk.Label(self.User_banking)
        self.USER_BANKING_INTERFACE_Reg.place(relx=0.252, rely=0.025, height=21
                                              , width=187)
        self.USER_BANKING_INTERFACE_Reg.configure(background="#d9d9d9")
        self.USER_BANKING_INTERFACE_Reg.configure(disabledforeground="#a3a3a3")
        self.USER_BANKING_INTERFACE_Reg.configure(font="-family {Verdana} -size 10 -weight bold")
        self.USER_BANKING_INTERFACE_Reg.configure(foreground="#000000")
        self.USER_BANKING_INTERFACE_Reg.configure(text='''USER BANKING INTERFACE''')

        self.Airtime_Recharge_Reg = tk.Label(self.User_banking)
        self.Airtime_Recharge_Reg.place(relx=0.029, rely=0.503, height=21
                                        , width=114)
        self.Airtime_Recharge_Reg.configure(background="#d9d9d9")
        self.Airtime_Recharge_Reg.configure(disabledforeground="#a3a3a3")
        self.Airtime_Recharge_Reg.configure(font="-family {Verdana} -size 10")
        self.Airtime_Recharge_Reg.configure(foreground="#000000")
        self.Airtime_Recharge_Reg.configure(text='''Airtime Recharge''')

        self.Bill_Payment = tk.Button(self.User_banking)
        self.Bill_Payment.place(relx=0.435, rely=0.276, height=24, width=77)
        self.Bill_Payment.configure(activebackground="#ececec")
        self.Bill_Payment.configure(activeforeground="#000000")
        self.Bill_Payment.configure(background="#808040")
        self.Bill_Payment.configure(disabledforeground="#a3a3a3")
        self.Bill_Payment.configure(font="-family {Verdana} -size 10 -weight bold")
        self.Bill_Payment.configure(foreground="#ffffff")
        self.Bill_Payment.configure(highlightbackground="#d9d9d9")
        self.Bill_Payment.configure(highlightcolor="black")
        self.Bill_Payment.configure(pady="0")
        self.Bill_Payment.configure(text='''Payment''')

        self.Bank_Transfer = tk.Button(self.User_banking)
        self.Bank_Transfer.place(relx=0.435, rely=0.402, height=24, width=77)
        self.Bank_Transfer.configure(activebackground="#ececec")
        self.Bank_Transfer.configure(activeforeground="#000000")
        self.Bank_Transfer.configure(background="#808040")
        self.Bank_Transfer.configure(disabledforeground="#a3a3a3")
        self.Bank_Transfer.configure(font="-family {Verdana} -size 10 -weight bold")
        self.Bank_Transfer.configure(foreground="#ffffff")
        self.Bank_Transfer.configure(highlightbackground="#d9d9d9")
        self.Bank_Transfer.configure(highlightcolor="black")
        self.Bank_Transfer.configure(pady="0")
        self.Bank_Transfer.configure(text='''Transfer''')

        self.Airtime_Recharge = tk.Button(self.User_banking)
        self.Airtime_Recharge.place(relx=0.435, rely=0.503, height=24, width=77)
        self.Airtime_Recharge.configure(activebackground="#ececec")
        self.Airtime_Recharge.configure(activeforeground="#000000")
        self.Airtime_Recharge.configure(background="#808040")
        self.Airtime_Recharge.configure(disabledforeground="#a3a3a3")
        self.Airtime_Recharge.configure(font="-family {Verdana} -size 10 -weight bold")
        self.Airtime_Recharge.configure(foreground="#ffffff")
        self.Airtime_Recharge.configure(highlightbackground="#d9d9d9")
        self.Airtime_Recharge.configure(highlightcolor="black")
        self.Airtime_Recharge.configure(pady="0")
        self.Airtime_Recharge.configure(text='''Recharge''')

        self.Having_A_Retract = tk.Label(self.User_banking)
        self.Having_A_Retract.place(relx=0.029, rely=0.603, height=21, width=124)

        self.Having_A_Retract.configure(background="#d9d9d9")
        self.Having_A_Retract.configure(disabledforeground="#a3a3a3")
        self.Having_A_Retract.configure(font="-family {Verdana} -size 10")
        self.Having_A_Retract.configure(foreground="#000000")
        self.Having_A_Retract.configure(text='''Having A Retract?''')

        self.Account_Officer = tk.Button(self.User_banking)
        self.Account_Officer.place(relx=0.435, rely=0.603, height=24, width=157)
        self.Account_Officer.configure(activebackground="#ececec")
        self.Account_Officer.configure(activeforeground="#000000")
        self.Account_Officer.configure(background="#808040")
        self.Account_Officer.configure(disabledforeground="#a3a3a3")
        self.Account_Officer.configure(font="-family {Verdana} -size 9")
        self.Account_Officer.configure(foreground="#ffffff")
        self.Account_Officer.configure(highlightbackground="#d9d9d9")
        self.Account_Officer.configure(highlightcolor="black")
        self.Account_Officer.configure(pady="0")
        self.Account_Officer.configure(text='''Contact Account Officer''')

        self.Back_Button = tk.Button(self.User_banking)
        self.Back_Button.place(relx=0.319, rely=0.754, height=24, width=67)
        self.Back_Button.configure(activebackground="#ececec")
        self.Back_Button.configure(activeforeground="#000000")
        self.Back_Button.configure(background="#808040")
        self.Back_Button.configure(disabledforeground="#a3a3a3")
        self.Back_Button.configure(font="-family {Verdana} -size 10 -weight bold")
        self.Back_Button.configure(foreground="#ffffff")
        self.Back_Button.configure(highlightbackground="#d9d9d9")
        self.Back_Button.configure(highlightcolor="black")
        self.Back_Button.configure(pady="0")
        self.Back_Button.configure(text='''<<<<<''')

        self.user_banking_logo = tk.Label(self.User_banking)
        self.user_banking_logo.place(relx=0.667, rely=0.854, height=51
                                     , width=104)
        self.user_banking_logo.configure(background="#d9d9d9")
        self.user_banking_logo.configure(disabledforeground="#a3a3a3")
        self.user_banking_logo.configure(foreground="#000000")
        photo_location = os.path.join(prog_location, "Azlogo3.jpg")
        global _img30
        _img30 = ImageTk.PhotoImage(file=photo_location)
        self.user_banking_logo.configure(image=_img30)
        self.user_banking_logo.configure(text='''Label''')

        # ---------------QUICK BILLS PAYMENT--------------------------
        self.quickBILLS_PAYMENT_Frame = tk.Frame(top)
        self.quickBILLS_PAYMENT_Frame.place(relx=0.183, rely=0.042, relheight=0.885
                                            , relwidth=0.575)
        self.quickBILLS_PAYMENT_Frame.configure(relief='groove')
        self.quickBILLS_PAYMENT_Frame.configure(borderwidth="2")
        self.quickBILLS_PAYMENT_Frame.configure(relief="groove")
        self.quickBILLS_PAYMENT_Frame.configure(background="#d9d9d9")

        self.quickBILLS_PAYMENT_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickBILLS_PAYMENT_Reg.place(relx=0.29, rely=0.052, height=22, width=131)

        self.quickBILLS_PAYMENT_Reg.configure(background="#d9d9d9")
        self.quickBILLS_PAYMENT_Reg.configure(disabledforeground="#a3a3a3")
        self.quickBILLS_PAYMENT_Reg.configure(font="-family {Verdana} -size 10 -weight bold")
        self.quickBILLS_PAYMENT_Reg.configure(foreground="#000000")
        self.quickBILLS_PAYMENT_Reg.configure(text='''BILLS PAYMENT''')

        self.quickVendor_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickVendor_Reg.place(relx=0.101, rely=0.176, height=23, width=63)
        self.quickVendor_Reg.configure(background="#d9d9d9")
        self.quickVendor_Reg.configure(disabledforeground="#a3a3a3")
        self.quickVendor_Reg.configure(font="-family {Verdana} -size 10")
        self.quickVendor_Reg.configure(foreground="#000000")
        self.quickVendor_Reg.configure(text='''Vendor''')

        qb = tk.StringVar()
        self.quickVendor_combo = ttk.Combobox(self.quickBILLS_PAYMENT_Frame)
        self.quickVendor_combo.place(relx=0.357, rely=0.176, relheight=0.054
                                     , relwidth=0.281)
        self.quickVendor_combo.configure(textvariable=qb)
        self.quickVendor_combo.configure(takefocus="")

        self.quickPlan_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickPlan_Reg.place(relx=0.101, rely=0.304, height=23, width=63)
        self.quickPlan_Reg.configure(background="#d9d9d9")
        self.quickPlan_Reg.configure(disabledforeground="#a3a3a3")
        self.quickPlan_Reg.configure(font="-family {Verdana} -size 10")
        self.quickPlan_Reg.configure(foreground="#000000")
        self.quickPlan_Reg.configure(text='''Plan''')

        qp = tk.StringVar()
        self.quickPlan__Combo = ttk.Combobox(self.quickBILLS_PAYMENT_Frame)
        self.quickPlan__Combo.place(relx=0.357, rely=0.304, relheight=0.054
                                    , relwidth=0.281)
        self.quickPlan__Combo.configure(textvariable=qp)
        self.quickPlan__Combo.configure(takefocus="")

        self.quickAccount_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickAccount_Reg.place(relx=0.101, rely=0.405, height=23, width=63)
        self.quickAccount_Reg.configure(background="#d9d9d9")
        self.quickAccount_Reg.configure(disabledforeground="#a3a3a3")
        self.quickAccount_Reg.configure(font="-family {Verdana} -size 10")
        self.quickAccount_Reg.configure(foreground="#000000")
        self.quickAccount_Reg.configure(text='''Account''')

        self.quickAccount_Entry = tk.Entry(self.quickBILLS_PAYMENT_Frame)
        self.quickAccount_Entry.place(relx=0.348, rely=0.402, height=20
                                      , relwidth=0.359)
        self.quickAccount_Entry.configure(background="white")
        self.quickAccount_Entry.configure(disabledforeground="#a3a3a3")
        self.quickAccount_Entry.configure(font="TkFixedFont")
        self.quickAccount_Entry.configure(foreground="#000000")
        self.quickAccount_Entry.configure(insertbackground="black")

        self.quickamount_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickamount_Reg.place(relx=0.101, rely=0.506, height=23, width=63)
        self.quickamount_Reg.configure(background="#d9d9d9")
        self.quickamount_Reg.configure(disabledforeground="#a3a3a3")
        self.quickamount_Reg.configure(font="-family {Verdana} -size 10")
        self.quickamount_Reg.configure(foreground="#000000")
        self.quickamount_Reg.configure(text='''Amount''')

        self.quickamount_Entry = tk.Entry(self.quickBILLS_PAYMENT_Frame)
        self.quickamount_Entry.place(relx=0.348, rely=0.504, height=20
                                     , relwidth=0.359)
        self.quickamount_Entry.configure(background="white")
        self.quickamount_Entry.configure(disabledforeground="#a3a3a3")
        self.quickamount_Entry.configure(font="TkFixedFont")
        self.quickamount_Entry.configure(foreground="#000000")
        self.quickamount_Entry.configure(insertbackground="black")

        self.quicknarration_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quicknarration_Reg.place(relx=0.101, rely=0.612, height=23, width=63)
        self.quicknarration_Reg.configure(background="#d9d9d9")
        self.quicknarration_Reg.configure(disabledforeground="#a3a3a3")
        self.quicknarration_Reg.configure(font="-family {Verdana} -size 10")
        self.quicknarration_Reg.configure(foreground="#000000")
        self.quicknarration_Reg.configure(text='''Narration''')

        self.quicknarration_Entry = tk.Entry(self.quickBILLS_PAYMENT_Frame)
        self.quicknarration_Entry.place(relx=0.348, rely=0.602, height=20, relwidth=0.359)
        self.quicknarration_Entry.configure(background="white")
        self.quicknarration_Entry.configure(disabledforeground="#a3a3a3")
        self.quicknarration_Entry.configure(font="TkFixedFont")
        self.quicknarration_Entry.configure(foreground="#000000")
        self.quicknarration_Entry.configure(insertbackground="black")

        self.quickpin_Reg = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickpin_Reg.place(relx=0.101, rely=0.696, height=23, width=33)
        self.quickpin_Reg.configure(background="#d9d9d9")
        self.quickpin_Reg.configure(disabledforeground="#a3a3a3")
        self.quickpin_Reg.configure(font="-family {Verdana} -size 10")
        self.quickpin_Reg.configure(foreground="#000000")
        self.quickpin_Reg.configure(text='''Pin''')

        self.quickpin_Entry = tk.Entry(self.quickBILLS_PAYMENT_Frame)
        self.quickpin_Entry.place(relx=0.348, rely=0.696, height=20, relwidth=0.359)
        self.quickpin_Entry.configure(background="white")
        self.quickpin_Entry.configure(disabledforeground="#a3a3a3")
        self.quickpin_Entry.configure(font="TkFixedFont")
        self.quickpin_Entry.configure(foreground="#000000")
        self.quickpin_Entry.configure(insertbackground="black")

        self.quickMake_Payment_Button = tk.Button(self.quickBILLS_PAYMENT_Frame)
        self.quickMake_Payment_Button.place(relx=0.101, rely=0.776, height=24
                                            , width=117)
        self.quickMake_Payment_Button.configure(activebackground="#ececec")
        self.quickMake_Payment_Button.configure(activeforeground="#000000")
        self.quickMake_Payment_Button.configure(background="#808040")
        self.quickMake_Payment_Button.configure(disabledforeground="#a3a3a3")
        self.quickMake_Payment_Button.configure(font="-family {Verdana} -size 10 -weight bold")
        self.quickMake_Payment_Button.configure(foreground="#ffffff")
        self.quickMake_Payment_Button.configure(highlightbackground="#d9d9d9")
        self.quickMake_Payment_Button.configure(highlightcolor="black")
        self.quickMake_Payment_Button.configure(pady="0")
        self.quickMake_Payment_Button.configure(text='''Make Payment''')

        self.quickCancel_Button = tk.Button(self.quickBILLS_PAYMENT_Frame)
        self.quickCancel_Button.place(relx=0.464, rely=0.776, height=24, width=77)
        self.quickCancel_Button.configure(activebackground="#ececec")
        self.quickCancel_Button.configure(activeforeground="#000000")
        self.quickCancel_Button.configure(background="#804040")
        self.quickCancel_Button.configure(disabledforeground="#a3a3a3")
        self.quickCancel_Button.configure(font="-family {Verdana} -size 10 -weight bold")
        self.quickCancel_Button.configure(foreground="#ffffff")
        self.quickCancel_Button.configure(highlightbackground="#d9d9d9")
        self.quickCancel_Button.configure(highlightcolor="black")
        self.quickCancel_Button.configure(pady="0")
        self.quickCancel_Button.configure(text='''Cancel''')

        self.quickbills_pay_logo = tk.Label(self.quickBILLS_PAYMENT_Frame)
        self.quickbills_pay_logo.place(relx=0.696, rely=0.871, height=41, width=94)
        self.quickbills_pay_logo.configure(background="#d9d9d9")
        self.quickbills_pay_logo.configure(disabledforeground="#a3a3a3")
        self.quickbills_pay_logo.configure(foreground="#000000")
        photo_location = os.path.join(prog_location, "Azlogo3.jpg")
        global _img61
        _img61 = ImageTk.PhotoImage(file=photo_location)
        self.quickbills_pay_logo.configure(image=_img61)
        self.quickbills_pay_logo.configure(text='''Label''')


if __name__ == '__main__':
    vp_start_gui()
