#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Aug 17, 2021 07:37:11 AM WAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import updatepin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    updatepin_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    updatepin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.update_pin = tk.Frame(top)
        self.update_pin.place(relx=0.2, rely=0.022, relheight=0.944
                , relwidth=0.575)
        self.update_pin.configure(relief='groove')
        self.update_pin.configure(borderwidth="2")
        self.update_pin.configure(relief="groove")
        self.update_pin.configure(background="#d9d9d9")

        self.update_pin_Label1 = tk.Label(self.update_pin)
        self.update_pin_Label1.place(relx=0.029, rely=0.024, height=41, width=84)

        self.update_pin_Label1.configure(background="#d9d9d9")
        self.update_pin_Label1.configure(disabledforeground="#a3a3a3")
        self.update_pin_Label1.configure(foreground="#000000")
        self.update_pin_Label1.configure(text='''Label''')

        self.update_pin_heading_Label1 = tk.Label(self.update_pin)
        self.update_pin_heading_Label1.place(relx=0.319, rely=0.047, height=31
                , width=214)
        self.update_pin_heading_Label1.configure(background="#d9d9d9")
        self.update_pin_heading_Label1.configure(disabledforeground="#a3a3a3")
        self.update_pin_heading_Label1.configure(font="-family {Verdana} -size 13 -weight bold")
        self.update_pin_heading_Label1.configure(foreground="#000000")
        self.update_pin_heading_Label1.configure(text='''UPDATE PIN''')

        self.newpin_update_Label1 = tk.Label(self.update_pin)
        self.newpin_update_Label1.place(relx=0.087, rely=0.282, height=21
                , width=140)
        self.newpin_update_Label1.configure(background="#d9d9d9")
        self.newpin_update_Label1.configure(disabledforeground="#a3a3a3")
        self.newpin_update_Label1.configure(foreground="#000000")
        self.newpin_update_Label1.configure(text='''New Pin''')

        self.update_new_pin_Entry1 = tk.Entry(self.update_pin)
        self.update_new_pin_Entry1.place(relx=0.522, rely=0.282, height=20
                , relwidth=0.388)
        self.update_new_pin_Entry1.configure(background="white")
        self.update_new_pin_Entry1.configure(disabledforeground="#a3a3a3")
        self.update_new_pin_Entry1.configure(font="TkFixedFont")
        self.update_new_pin_Entry1.configure(foreground="#000000")
        self.update_new_pin_Entry1.configure(insertbackground="black")

        self.confirm_pin_update_Label1_1 = tk.Label(self.update_pin)
        self.confirm_pin_update_Label1_1.place(relx=0.087, rely=0.447, height=21
                , width=134)
        self.confirm_pin_update_Label1_1.configure(activebackground="#f9f9f9")
        self.confirm_pin_update_Label1_1.configure(activeforeground="black")
        self.confirm_pin_update_Label1_1.configure(background="#d9d9d9")
        self.confirm_pin_update_Label1_1.configure(disabledforeground="#a3a3a3")
        self.confirm_pin_update_Label1_1.configure(foreground="#000000")
        self.confirm_pin_update_Label1_1.configure(highlightbackground="#d9d9d9")
        self.confirm_pin_update_Label1_1.configure(highlightcolor="black")
        self.confirm_pin_update_Label1_1.configure(text='''Confirrm New Pin''')

        self.confirm_new_pin_Entry1_1 = tk.Entry(self.update_pin)
        self.confirm_new_pin_Entry1_1.place(relx=0.522, rely=0.447, height=20
                , relwidth=0.388)
        self.confirm_new_pin_Entry1_1.configure(background="white")
        self.confirm_new_pin_Entry1_1.configure(disabledforeground="#a3a3a3")
        self.confirm_new_pin_Entry1_1.configure(font="TkFixedFont")
        self.confirm_new_pin_Entry1_1.configure(foreground="#000000")
        self.confirm_new_pin_Entry1_1.configure(highlightbackground="#d9d9d9")
        self.confirm_new_pin_Entry1_1.configure(highlightcolor="black")
        self.confirm_new_pin_Entry1_1.configure(insertbackground="black")
        self.confirm_new_pin_Entry1_1.configure(selectbackground="blue")
        self.confirm_new_pin_Entry1_1.configure(selectforeground="white")

        self.Save_update_pin = tk.Button(self.update_pin)
        self.Save_update_pin.place(relx=0.406, rely=0.612, height=24, width=67)
        self.Save_update_pin.configure(activebackground="#ececec")
        self.Save_update_pin.configure(activeforeground="#000000")
        self.Save_update_pin.configure(background="#808040")
        self.Save_update_pin.configure(disabledforeground="#a3a3a3")
        self.Save_update_pin.configure(font="-family {Verdana} -size 9 -weight bold")
        self.Save_update_pin.configure(foreground="#ffffff")
        self.Save_update_pin.configure(highlightbackground="#d9d9d9")
        self.Save_update_pin.configure(highlightcolor="black")
        self.Save_update_pin.configure(pady="0")
        self.Save_update_pin.configure(text='''Save''')

        self.back_update_pin_1 = tk.Button(self.update_pin)
        self.back_update_pin_1.place(relx=0.696, rely=0.612, height=24, width=67)

        self.back_update_pin_1.configure(activebackground="#ececec")
        self.back_update_pin_1.configure(activeforeground="#000000")
        self.back_update_pin_1.configure(background="#804040")
        self.back_update_pin_1.configure(disabledforeground="#a3a3a3")
        self.back_update_pin_1.configure(font="-family {Verdana} -size 9 -weight bold")
        self.back_update_pin_1.configure(foreground="#ffffff")
        self.back_update_pin_1.configure(highlightbackground="#d9d9d9")
        self.back_update_pin_1.configure(highlightcolor="black")
        self.back_update_pin_1.configure(pady="0")
        self.back_update_pin_1.configure(text='''Back''')

if __name__ == '__main__':
    vp_start_gui()





